# Generated by Django 5.1.6 on 2025-02-18 19:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='profile_image', max_length=255, verbose_name='image'),
        ),
    ]
