# Generated by Django 5.1.6 on 2025-02-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_newuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
