# Generated by Django 5.1.6 on 2025-02-18 19:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_featured_image_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='event_image', max_length=255, verbose_name='Event Image'),
        ),
    ]
