# Generated by Django 5.1.6 on 2025-03-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
